# Generated by Django 6.0.1 on 2026-02-22 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Inscricao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=80)),
                ('sobrenome', models.CharField(max_length=120)),
                ('idade', models.PositiveSmallIntegerField()),
                ('telefone', models.CharField(max_length=30)),
                ('ministerio', models.CharField(choices=[('canhotinho', 'Canhotinho'), ('sao_joao', 'São João'), ('logradouro', 'Logradouro'), ('jurema', 'Jurema'), ('jupi', 'Jupi'), ('correntes_bom_conselho', 'Correntes Bom Conselho'), ('garanhuns', 'Garanhuns')], max_length=30)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
